"""This module defines constants for fridge object detection module."""

CAMERA_RECONNECT_WAIT_TIME_SECS = 5

REQUEST_MAX_RETRIES = 3
REQUEST_BACKOFF_FACTOR = 0.5

QUEUE_MAX_SIZE = 1
QUEUE_GET_TIMEOUT = 1
QUEUE_PUT_TIMEOUT = 1

LOCK_TIMEOUT = 0.5

E2E_TEST_TIMEOUT = 60
